#!/bin/bash

BASHLIB_ATTRIBUTES_regular="0"
BASHLIB_ATTRIBUTES_bold="01"
BASHLIB_ATTRIBUTES_dark="02"
BASHLIB_ATTRIBUTES_italic="02"
BASHLIB_ATTRIBUTES_underline="04"
BASHLIB_ATTRIBUTES_reverse="07"
BASHLIB_ATTRIBUTES_strike="09"

BASHLIB_COLOR_black="30"
BASHLIB_COLOR_red="31"
BASHLIB_COLOR_green="32"
BASHLIB_COLOR_yellow="33"
BASHLIB_COLOR_blue="34"
BASHLIB_COLOR_magenta="35"
BASHLIB_COLOR_cyan="36"
BASHLIB_COLOR_white="37"

BASHLIB_BACKGROUND_black="40"
BASHLIB_BACKGROUND_red="41"
BASHLIB_BACKGROUND_green="42"
BASHLIB_BACKGROUND_yellow="43"
BASHLIB_BACKGROUND_blue="44"
BASHLIB_BACKGROUND_magenta="45"
BASHLIB_BACKGROUND_cyan="46"
BASHLIB_BACKGROUND_white="47"

function color_init() {
    
}

